services:
  postgres-db:
    image: postgres:14
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Wrong123
      POSTGRES_DB: BookStore

  postgres-client:
    image: postgres:14
    container_name: psql-client
    depends_on:
      - postgres-db
    entrypoint: [ "tail", "-f", "/dev/null" ]

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  bookstore_springboot_app:
    build:
      context: ./
    container_name: bookstore_springboot_app
    depends_on:
      - postgres-db
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BookStore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Wrong123
      SPRING_REDIS_HOST: redis_cache
      SPRING_REDIS_PORT: 6379

  frontend:
    build:
      context: ./Frontend
    container_name: Frontend
    ports:
      - "3000:80"
    depends_on:
        - bookstore_springboot_app



volumes:
  postgres_data:
    driver: local
