spring:
  application:
    name: bookstore

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASS}@bookstore.sitltde.mongodb.net/bookstore?retryWrites=true&w=majority
      database: bookstore
