server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BookStore
    username: admin
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
