
#  This file tells Spring Boot how to connect to your PostgreSQL database:
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BookStore
    username: my-user
    password: my-password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
# Uncomment the following lines to switch to H2 configuration
#    # Enable H2 console
#    spring.h2.console.enabled=true
#    spring.h2.console.path=/h2-console
#
#    # Database connection settings
#    spring.datasource.url=jdbc:h2:mem:my-db
#    spring.datasource.driverClassName=org.h2.Driver
#    spring.datasource.username=sa
#    spring.datasource.password=
#    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#    # Optional: auto-create tables
#    spring.jpa.hibernate.ddl-auto=update



# Uncomment the following lines to switch to MySQL configuration

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/my-db
#    username: my-user
#    password: user-password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#  # Optional: Enable SQL logging
#  sql:
#    init:
#      mode: always
#
## Optional: Server port
#server:
#  port: 8080
